INSERT INTO app_user (name, email, password) VALUES
                                                 ('Rahul Sharma', 'rahul.sharma@gmail.com', '$2a$10$exampleHash1'),
                                                 ('Ananya Gupta', 'ananya.gupta@gmail.com', '$2a$10$exampleHash2'),
                                                 ('Vikram Mehta', 'vikram.mehta@gmail.com', '$2a$10$exampleHash3'),
                                                 ('Priya Singh', 'priya.singh@gmail.com', '$2a$10$exampleHash4'),
                                                 ('Arjun Reddy', 'arjun.reddy@gmail.com', '$2a$10$exampleHash5'),
                                                 ('Nisha Jain', 'nisha.jain@gmail.com', '$2a$10$exampleHash6'),
                                                 ('Karan Kapoor', 'karan.kapoor@gmail.com', '$2a$10$exampleHash7'),
                                                 ('Sneha Verma', 'sneha.verma@gmail.com', '$2a$10$exampleHash8'),
                                                 ('Aman Patel', 'aman.patel@gmail.com', '$2a$10$exampleHash9'),
                                                 ('Riya Malhotra', 'riya.malhotra@gmail.com', '$2a$10$exampleHash10'),
                                                 ('Devansh Chawla', 'devansh.chawla@gmail.com', '$2a$10$exampleHash11'),
                                                 ('Meera Nair', 'meera.nair@gmail.com', '$2a$10$exampleHash12'),
                                                 ('Rohit Bhatia', 'rohit.bhatia@gmail.com', '$2a$10$exampleHash13'),
                                                 ('Ishita Roy', 'ishita.roy@gmail.com', '$2a$10$exampleHash14'),
                                                 ('Aakash Singh', 'aakash.singh@gmail.com', '$2a$10$exampleHash15'),
                                                 ('Simran Kaur', 'simran.kaur@gmail.com', '$2a$10$exampleHash16'),
                                                 ('Kabir Khan', 'kabir.khan@gmail.com', '$2a$10$exampleHash17'),
                                                 ('Neha Chopra', 'neha.chopra@gmail.com', '$2a$10$exampleHash18'),
                                                 ('Aditya Anand', 'aditya.anand@gmail.com', '$2a$10$exampleHash19'),
                                                 ('Pooja Das', 'pooja.das@gmail.com', '$2a$10$exampleHash20'),
                                                 ('Yash Malhotra', 'yash.malhotra@gmail.com', '$2a$10$exampleHash21'),
                                                 ('Shreya Iyer', 'shreya.iyer@gmail.com', '$2a$10$exampleHash22'),
                                                 ('Naveen Sharma', 'naveen.sharma@gmail.com', '$2a$10$exampleHash23'),
                                                 ('Vidya Krishnan', 'vidya.krishnan@gmail.com', '$2a$10$exampleHash24'),
                                                 ('Siddharth Jain', 'siddharth.jain@gmail.com', '$2a$10$exampleHash25'),
                                                 ('Aditi Mishra', 'aditi.mishra@gmail.com', '$2a$10$exampleHash26'),
                                                 ('Ravi Agarwal', 'ravi.agarwal@gmail.com', '$2a$10$exampleHash27'),
                                                 ('Tanya Sen', 'tanya.sen@gmail.com', '$2a$10$exampleHash28'),
                                                 ('Kavya Dubey', 'kavya.dubey@gmail.com', '$2a$10$exampleHash29'),
                                                 ('Sourabh Rathi', 'sourabh.rathi@gmail.com', '$2a$10$exampleHash30'),
                                                 ('Rachit Verma', 'rachit.verma@gmail.com', '$2a$10$exampleHash31'),
                                                 ('Neeraj Malhotra', 'neeraj.malhotra@gmail.com', '$2a$10$exampleHash32'),
                                                 ('Asha Rani', 'asha.rani@gmail.com', '$2a$10$exampleHash33'),
                                                 ('Mohit Sharma', 'mohit.sharma@gmail.com', '$2a$10$exampleHash34'),
                                                 ('Lavanya Mehta', 'lavanya.mehta@gmail.com', '$2a$10$exampleHash35'),
                                                 ('Nitin Gupta', 'nitin.gupta@gmail.com', '$2a$10$exampleHash36'),
                                                 ('Pallavi Jha', 'pallavi.jha@gmail.com', '$2a$10$exampleHash37'),
                                                 ('Rajesh Iyer', 'rajesh.iyer@gmail.com', '$2a$10$exampleHash38'),
                                                 ('Divya Anand', 'divya.anand@gmail.com', '$2a$10$exampleHash39'),
                                                 ('Sudhir Rathi', 'sudhir.rathi@gmail.com', '$2a$10$exampleHash40'),
                                                 ('Ankita Sen', 'ankita.sen@gmail.com', '$2a$10$exampleHash41'),
                                                 ('Rahul Chauhan', 'rahul.chauhan@gmail.com', '$2a$10$exampleHash42'),
                                                 ('Ishaan Thakur', 'ishaan.thakur@gmail.com', '$2a$10$exampleHash43'),
                                                 ('Poonam Nair', 'poonam.nair@gmail.com', '$2a$10$exampleHash44'),
                                                 ('Kartik Kapoor', 'kartik.kapoor@gmail.com', '$2a$10$exampleHash45');

INSERT INTO user_roles (user_id, roles) VALUES
                                            (1, 'RIDER'),
                                            (2, 'RIDER'),
                                            (2, 'DRIVER'),
                                            (3, 'RIDER'),
                                            (3, 'DRIVER'),
                                            (4, 'RIDER'),
                                            (4, 'DRIVER'),
                                            (5, 'RIDER'),
                                            (5, 'DRIVER'),
                                            (6, 'RIDER'),
                                            (6, 'DRIVER'),
                                            (7, 'RIDER'),
                                            (7, 'DRIVER'),
                                            (8, 'RIDER'),
                                            (8, 'DRIVER'),
                                            (9, 'RIDER'),
                                            (9, 'DRIVER'),
                                            (10, 'RIDER'),
                                            (10, 'DRIVER'),
                                            (11, 'RIDER'),
                                            (11, 'DRIVER'),
                                            (12, 'RIDER'),
                                            (12, 'DRIVER'),
                                            (13, 'RIDER'),
                                            (13, 'DRIVER'),
                                            (14, 'RIDER'),
                                            (14, 'DRIVER'),
                                            (15, 'RIDER'),
                                            (15, 'DRIVER'),
                                            (16, 'RIDER'),
                                            (16, 'DRIVER'),
                                            (17, 'RIDER'),
                                            (17, 'DRIVER'),
                                            (18, 'RIDER'),
                                            (18, 'DRIVER'),
                                            (19, 'RIDER'),
                                            (19, 'DRIVER'),
                                            (20, 'RIDER'),
                                            (20, 'DRIVER'),
                                            (21, 'RIDER'),
                                            (21, 'DRIVER'),
                                            (22, 'RIDER'),
                                            (22, 'DRIVER'),
                                            (23, 'RIDER'),
                                            (23, 'DRIVER'),
                                            (24, 'RIDER'),
                                            (24, 'DRIVER'),
                                            (25, 'RIDER'),
                                            (25, 'DRIVER'),
                                            (26, 'RIDER'),
                                            (26, 'DRIVER'),
                                            (27, 'RIDER'),
                                            (27, 'DRIVER'),
                                            (28, 'RIDER'),
                                            (28, 'DRIVER'),
                                            (29, 'RIDER'),
                                            (29, 'DRIVER'),
                                            (30, 'RIDER'),
                                            (30, 'DRIVER'),
                                            (31, 'RIDER'),
                                            (31, 'DRIVER'),
                                            (32, 'RIDER'),
                                            (32, 'DRIVER'),
                                            (33, 'RIDER'),
                                            (33, 'DRIVER'),
                                            (34, 'RIDER'),
                                            (34, 'DRIVER'),
                                            (35, 'RIDER'),
                                            (35, 'DRIVER'),
                                            (36, 'RIDER'),
                                            (36, 'DRIVER'),
                                            (37, 'RIDER'),
                                            (37, 'DRIVER'),
                                            (38, 'RIDER'),
                                            (38, 'DRIVER'),
                                            (39, 'RIDER'),
                                            (39, 'DRIVER'),
                                            (40, 'RIDER'),
                                            (40, 'DRIVER'),
                                            (41, 'RIDER'),
                                            (41, 'DRIVER'),
                                            (42, 'RIDER'),
                                            (42, 'DRIVER'),
                                            (43, 'RIDER'),
                                            (43, 'DRIVER'),
                                            (44, 'RIDER'),
                                            (44, 'DRIVER'),
                                            (45, 'RIDER'),
                                            (45, 'DRIVER');

INSERT INTO rider (id, user_id,rating) VALUES (1,1,4.9);

INSERT INTO driver(id, user_id, rating, available, current_location) VALUES
                                                                            (2, 2, 4.7, true, ST_GeomFromText('POINT(72.8777 19.0760)', 4326)),
                                                                            (3, 3, 4.5, false, ST_GeomFromText('POINT(72.8650 19.0910)', 4326)),
                                                                            (4, 4, 4.9, true, ST_GeomFromText('POINT(72.8508 19.0645)', 4326)),
                                                                            (5, 5, 4.8, true, ST_GeomFromText('POINT(72.8900 19.0765)', 4326)),
                                                                            (6, 6, 4.2, false, ST_GeomFromText('POINT(72.8704 19.0628)', 4326)),
                                                                            (7, 7, 4.3, true, ST_GeomFromText('POINT(72.8625 19.0833)', 4326)),
                                                                            (8, 8, 4.6, true, ST_GeomFromText('POINT(72.8803 19.0722)', 4326)),
                                                                            (9, 9, 4.4, true, ST_GeomFromText('POINT(72.8555 19.0705)', 4326)),
                                                                            (10, 10, 4.7, false, ST_GeomFromText('POINT(72.8659 19.0580)', 4326)),
                                                                            (11, 11, 4.1, true, ST_GeomFromText('POINT(72.8680 19.0821)', 4326)),
                                                                            (12, 12, 4.8, true, ST_GeomFromText('POINT(72.8585 19.0778)', 4326)),
                                                                            (13, 13, 4.9, true, ST_GeomFromText('POINT(72.8758 19.0654)', 4326)),
                                                                            (14, 14, 4.6, false, ST_GeomFromText('POINT(72.8400 19.0840)', 4326)),
                                                                            (15, 15, 4.5, true, ST_GeomFromText('POINT(72.8690 19.0639)', 4326)),
                                                                            (16, 16, 4.4, true, ST_GeomFromText('POINT(72.8577 19.0855)', 4326)),
                                                                            (17, 17, 4.7, false, ST_GeomFromText('POINT(72.8609 19.0780)', 4326)),
                                                                            (18, 18, 4.8, true, ST_GeomFromText('POINT(72.8833 19.0753)', 4326)),
                                                                            (19, 19, 4.3, true, ST_GeomFromText('POINT(72.8495 19.0891)', 4326)),
                                                                            (20, 20, 4.6, true, ST_GeomFromText('POINT(72.8785 19.0795)', 4326)),
                                                                            (21, 21, 4.9, true, ST_GeomFromText('POINT(72.8501 19.0744)', 4326)),
                                                                            (22, 22, 4.5, false, ST_GeomFromText('POINT(72.8602 19.0611)', 4326)),
                                                                            (23, 23, 4.8, true, ST_GeomFromText('POINT(72.8564 19.0677)', 4326)),
                                                                            (24, 24, 4.7, true, ST_GeomFromText('POINT(72.8828 19.0763)', 4326)),
                                                                            (25, 25, 4.2, false, ST_GeomFromText('POINT(72.8734 19.0812)', 4326)),
                                                                            (26, 26, 4.6, true, ST_GeomFromText('POINT(72.8519 19.0721)', 4326)),
                                                                            (27, 27, 4.3, true, ST_GeomFromText('POINT(72.8857 19.0659)', 4326)),
                                                                            (28, 28, 4.4, true, ST_GeomFromText('POINT(72.8676 19.0832)', 4326)),
                                                                            (29, 29, 4.5, false, ST_GeomFromText('POINT(72.8709 19.0748)', 4326)),
                                                                            (30, 30, 4.9, true, ST_GeomFromText('POINT(72.8553 19.0666)', 4326)),
                                                                            (31, 31, 4.1, true, ST_GeomFromText('POINT(72.8789 19.0770)', 4326)),
                                                                            (32, 32, 4.8, false, ST_GeomFromText('POINT(72.8598 19.0851)', 4326)),
                                                                            (33, 33, 4.7, true, ST_GeomFromText('POINT(72.8739 19.0622)', 4326)),
                                                                            (34, 34, 4.4, true, ST_GeomFromText('POINT(72.8800 19.0740)', 4326)),
                                                                            (35, 35, 4.6, false, ST_GeomFromText('POINT(72.8588 19.0890)', 4326)),
                                                                            (36, 36, 4.3, true, ST_GeomFromText('POINT(72.8611 19.0633)', 4326)),
                                                                            (37, 37, 4.9, true, ST_GeomFromText('POINT(72.8682 19.0802)', 4326)),
                                                                            (38, 38, 4.8, true, ST_GeomFromText('POINT(72.8575 19.0715)', 4326)),
                                                                            (39, 39, 4.7, false, ST_GeomFromText('POINT(72.8654 19.0757)', 4326)),
                                                                            (40, 40, 4.5, true, ST_GeomFromText('POINT(72.8628 19.0628)', 4326)),
                                                                            (41, 41, 4.6, true, ST_GeomFromText('POINT(72.8777 19.0799)', 4326)),
                                                                            (42, 42, 4.2, false, ST_GeomFromText('POINT(72.8720 19.0675)', 4326)),
                                                                            (43, 43, 4.8, true, ST_GeomFromText('POINT(72.8515 19.0815)', 4326)),
                                                                            (44, 44, 4.4, true, ST_GeomFromText('POINT(72.8890 19.0708)', 4326)),
                                                                            (45, 45, 4.5, true, ST_GeomFromText('POINT(72.8778 19.0745)', 4326));

